# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LrDqcrga8py-9TnbbL3uZshl6woKxLL1
"""

def check_correct(field, turn):
  a=turn[0]
  b=turn[1]
  if field[a][b]!=0:
    return False
  else: 
    return True